/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitemafamalog;
import Controlador.SolicitudSuministroBL;
import Controlador.PrioridadBL;
import Modelo.SolicitudSuministro;
import Modelo.Prioridad;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Andre
 */
public class ListaSolicitudesSuministro extends javax.swing.JFrame {
    private SolicitudSuministroBL gestorSolicudSuministro = new SolicitudSuministroBL();
    private PrioridadBL gestorPrioridad = new PrioridadBL();
    private ArrayList<SolicitudSuministro> listaSolSuministro;
    /**
     * Creates new form ListaSolicitudesSuministro
     */
    public ListaSolicitudesSuministro() {
        initComponents();
        listaSolSuministro = gestorSolicudSuministro.obtenerListaSolicitudSuministro();        
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel)tableLstSolicitudesSuministro.getModel();
        Object [] fila = new Object [6];
        for(int i=0; i<listaSolSuministro.size(); i++){
            fila[0] = listaSolSuministro.get(i).getCodigoSolicitudSuministro();
            DateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            String date = formatter1.format(listaSolSuministro.get(i).getFechaPeticion());
            fila[1] = date;
            DateFormat formatter2 = new SimpleDateFormat("dd/MM/yyyy");
            String date2 = formatter2.format(listaSolSuministro.get(i).getFechaLimite());            
            fila[2] = date2;
            String nombrePrioridad = gestorPrioridad.obtenerNombre(listaSolSuministro.get(i).getPrioridad().getIdPrioridad());
            listaSolSuministro.get(i).getPrioridad().setNombre(nombrePrioridad);
            fila[3] = nombrePrioridad;
            fila[4] = listaSolSuministro.get(i).getInstitucion();
            modelo.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLstSolicitudesSuministro = new javax.swing.JTable();
        btnEliminarSolicitud = new javax.swing.JButton();
        btnVerSolicitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista Solicitudes Suministro");

        tableLstSolicitudesSuministro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Solicitud", "Fecha Peticion", "Fecha limite", "Prioridad", "Institucion", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableLstSolicitudesSuministro.setName("tableLstSolicitudesSuministro"); // NOI18N
        jScrollPane1.setViewportView(tableLstSolicitudesSuministro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnEliminarSolicitud.setText("Eliminar Solicitud");
        btnEliminarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSolicitudActionPerformed(evt);
            }
        });

        btnVerSolicitud.setText("Ver Solicitud");
        btnVerSolicitud.setName("btnVerSolicitud"); // NOI18N
        btnVerSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerSolicitud)
                .addGap(26, 26, 26)
                .addComponent(btnEliminarSolicitud)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarSolicitud)
                    .addComponent(btnVerSolicitud))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSolicitudActionPerformed
        int index = tableLstSolicitudesSuministro.getSelectedRow();
        SolicitudSuministro seleccionado = listaSolSuministro.get(index);
        VerSolicitudSuministro fmr = new VerSolicitudSuministro(seleccionado, this);
        fmr.setSolicitud(seleccionado);
        fmr.setVisible(true);
        ListaSolicitudesSuministro.this.dispose();
    }//GEN-LAST:event_btnVerSolicitudActionPerformed

    private void btnEliminarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSolicitudActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableLstSolicitudesSuministro.getModel();
        for (int i=0;i<model.getRowCount();i++) {
              Boolean checked=(Boolean)model.getValueAt(i,5);
              if (checked!=null && checked) {
                   SolicitudSuministro s = listaSolSuministro.get(i);
                   gestorSolicudSuministro.eliminarSolicitudSuministro(s.getCodigoSolicitudSuministro());
                   model.removeRow(i);
                   i--;
              }
        }
    }//GEN-LAST:event_btnEliminarSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSolicitudesSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSolicitudesSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSolicitudesSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSolicitudesSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaSolicitudesSuministro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarSolicitud;
    private javax.swing.JButton btnVerSolicitud;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLstSolicitudesSuministro;
    // End of variables declaration//GEN-END:variables
}
